# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('booking_fee', models.DecimalField(decimal_places=2, max_digits=4)),
                ('profile_image', models.ImageField(upload_to='images')),
                ('profile_description', models.TextField()),
                ('contact_name', models.CharField(max_length=60)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='base_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Location'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre_category',
            field=models.ManyToManyField(to='artists.Genre'),
        ),
    ]
